
running 1 test
test tests::math ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 5 tests
test tests::basic_math ... ignored
test mymod::foo::tests::math ... ok
test mymod::tests::math ... ok
test tests::nested::nested_math ... ok
test tests::failed_math ... FAILED

failures:

---- tests::failed_math stdout ----
thread 'tests::failed_math' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`', src/main.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::failed_math

test result: FAILED. 3 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s
